; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{16F34288-25AF-446D-B644-8A24FD210B15}
AppName=InstantScale
AppVersion=1.0
;AppVerName=InstantScale 1.0
AppPublisherURL=https://github.com/Jrribas/InstantScale
AppSupportURL=https://github.com/Jrribas/InstantScale
AppUpdatesURL=https://github.com/Jrribas/InstantScale
DefaultDirName={pf}\InstantScale
DefaultGroupName=InstantScale
AllowNoIcons=yes
LicenseFile=C:\Users\Farinha\Documents\GitHub\InstantScale\License.txt
OutputDir=C:\Users\Farinha\Desktop\dist
OutputBaseFilename=setup-InstantScale-v1
SetupIconFile=C:\Users\Farinha\Documents\GitHub\InstantScale\icon.ico
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "portuguese"; MessagesFile: "compiler:Languages\Portuguese.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\Farinha\Documents\GitHub\InstantScale\build\exe.win-amd64-3.6\InstantScale.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\Farinha\Documents\GitHub\InstantScale\build\exe.win-amd64-3.6\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\InstantScale"; Filename: "{app}\InstantScale.exe"
Name: "{group}\{cm:ProgramOnTheWeb,InstantScale}"; Filename: "https://github.com/Jrribas/InstantScale"
Name: "{group}\{cm:UninstallProgram,InstantScale}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\InstantScale"; Filename: "{app}\InstantScale.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\InstantScale.exe"; Description: "{cm:LaunchProgram,InstantScale}"; Flags: nowait postinstall skipifsilent

